### ISSUE TITLE
Hamburger menu

### ISSUE THREAD

**Issue by lubelg** [galasa-dev-archives/webui-old#62]
On my MacBook Pro with an external 4k screen the hamburger menu doesn't render well on Firefox, Safari or Vivaldi (Chrome) - the middle two bars are antialiased, the top & bottom are crisp
![image](https://user-images.githubusercontent.com/61017744/108220455-a5db9e80-712e-11eb-9a55-0eae97df9a89.png)
This page may be helpful https://github.com/carbon-design-system/carbon-icons-angular - I presume you're using a Carbon SVG icon at its native size (one from: 16, 20, 24, or 32, with no rescaling)

The hover state needs a little adjustment to the colour and possibly to layout in Firefox
![image](https://user-images.githubusercontent.com/61017744/108220725-f226de80-712e-11eb-897f-bb2f1cb0695c.png)

- The background colour needs to be the same as the hover colour for the Galasa icon. (See Will's Sketch file where he's put the styleguide). 
- Also, on my Firefox (85.0.2) but not on Safari or Vivaldi, the hover colour doesn't reach the top or bottom of the header bar?

![image](https://user-images.githubusercontent.com/61017744/108221997-45e5f780-7130-11eb-90c6-875ebc1abf97.png)

(In terms of size (not colour), it correctly renders like this on Safari and Vivaldi)
![image](https://user-images.githubusercontent.com/61017744/108221870-26e76580-7130-11eb-946e-1e041c3d3650.png)

In Will's Sketch style guide, he has specified a three bar hamburger menu, not four bar. Will will be able to supply the correct SVG icon for that, if he hasn't already done so.

**Comment by Michael-Baylis** [comment]
Please raise issues in the Project Management repo

https://github.com/galasa-dev/projectmanagement/issues
