### ISSUE TITLE
Dashboard - or not?

### ISSUE THREAD

**Issue by lubelg** [galasa-dev-archives/webui-old#63]
This page isn't a dashboard and is more of a 'quick start' or 'Getting started' page - (We may want a dashboard too but we'd need to design a dashboard as a separate exercise, with a little research into user needs)

In order to fix this, please can we ditch the title in the header bar and instead increase the size of the 'Getting started' title on the left end of the grey section to 1.75rem (details of the rem/px implications in Will's styleguide). This will give this title the appearance of being higher in the title hierarchy and therefore promote it to be the page title

**Comment by Michael-Baylis** [comment]
Please raise all issues in the Project Management repo so they can be tracked.

https://github.com/galasa-dev/projectmanagement/issues
